services:
  - type: web
    name: wander-wise-backend
    env: python
    region: singapore  # Choose the region closest to your users
    plan: free
    healthCheckPath: /
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: backend.wsgi:app
    autoDeploy: true
    envVars:
      - key: AMADEUS_CLIENT_ID
        value: QuW8JPfhmusHqJ5RKx1HS58M9wORpb0G
      - key: AMADEUS_CLIENT_SECRET
        value: H3PhNDASolbgLFpV
      - key: OPENTRIPMAP_API_KEY
        value: 5ae2e3f221c38a28845f05b6e7c2251358c940672c1354c11888f5ab
    buildFilter:
      paths:
      - backend/**
      - requirements.txt
      - wsgi.py